#version: "3.8"

services:
  hello-app:
    build: ./apps/hello-app
    working_dir: /app
    command: sh -c "npm install --production --silent && node index.js"
    environment:
      - PORT=8080
    volumes:
      - ./apps/hello-app:/app
    expose:
      - "8080"

  time-app:
    build: ./apps/time-app
    working_dir: /app
    command: sh -c "npm install --production --silent && node index.js"
    environment:
      - PORT=8081
    volumes:
      - ./apps/time-app:/app
    expose:
      - "8081"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80" # host:8080 -> nginx:80
    volumes:
      - ./nginx/multi-apps.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - hello-app
      - time-app
