#version: "3.8"

services:
  hello-app:
    build: ./apps/hello-app
    working_dir: /app
    command: sh -c "npm install --production --silent && node index.js"
    environment:
      - PORT=8080
    volumes:
      - ./apps/hello-app:/app
    expose:
      - "8080"

  time-app:
    build: ./apps/time-app
    working_dir: /app
    command: sh -c "npm install --production --silent && node index.js"
    environment:
      - PORT=8081
    volumes:
      - ./apps/time-app:/app
    expose:
      - "8081"

  cal:
    build: ./apps/cal
    working_dir: /app
    command: sh -c "npm install --production --silent && node index.js"
    environment:
      - PORT=8083
    volumes:
      - ./apps/cal:/app
    expose:
      - "8083"

  contact-db:
    image: postgres:15-alpine
    container_name: contact_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contactdb
    volumes:
      - ../contacts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - contact_pgdata:/var/lib/postgresql/data
    expose:
      - "5432"

  contact-server:
    build: ../contacts/server
    container_name: contact_server
    expose:
      - "5000"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'node -e "require(''http'').get(''http://localhost:5000/health'', res=>{process.exit(res.statusCode===200?0:1)}).on(''error'',()=>process.exit(1))"',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: contact-db
      DB_NAME: contactdb
      DB_PORT: 5432
    depends_on:
      - contact-db

  contact-client:
    build:
      context: ../contacts/client
      dockerfile: Dockerfile
    volumes:
      - ../contacts/nginx/multi-apps/default.conf:/etc/nginx/conf.d/default.conf
    container_name: contact_client
    ports:
      - "8082:80"
    depends_on:
      - contact-server

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80" # host:80 -> nginx:80
      - "443:443" # host:443 -> nginx:443
    volumes:
      - ./nginx/multi-apps.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/certbot/conf:/etc/letsencrypt:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
    depends_on:
      - hello-app
      - time-app
      - cal
      - contact-client

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "certbot certonly --webroot -w /var/www/certbot -d localtower.org --non-interactive --agree-tos --email admin@localtower.org --keep-until-expiring || true"
    depends_on:
      - nginx

volumes:
  contact_pgdata:
