#version: "3.8"

services:
  hello-app:
    build: ./apps/hello-app
    working_dir: /app
    command: sh -c "npm install --production --silent && node index.js"
    environment:
      - PORT=8080
    volumes:
      - ./apps/hello-app:/app
    expose:
      - "8080"

  time-app:
    build: ./apps/time-app
    working_dir: /app
    command: sh -c "npm install --production --silent && node index.js"
    environment:
      - PORT=8081
    volumes:
      - ./apps/time-app:/app
    expose:
      - "8081"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80" # host:80 -> nginx:80
      - "443:443" # host:443 -> nginx:443
    volumes:
      - ./nginx/multi-apps.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/certbot/conf:/etc/letsencrypt:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
    depends_on:
      - hello-app
      - time-app

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "certbot certonly --webroot -w /var/www/certbot -d localtower.org --non-interactive --agree-tos --email admin@localtower.org --keep-until-expiring || true"
    depends_on:
      - nginx
