#version: "3.8"

services:
  hello-app:
    environment:
      - NODE_ENV=development
    command: sh -c "npm install --silent && node index.js"
    volumes:
      - ./apps/hello-app:/app:delegated
      - /app/node_modules
    restart: unless-stopped

  time-app:
    environment:
      - NODE_ENV=development
    command: sh -c "npm install --silent && node index.js"
    volumes:
      - ./apps/time-app:/app:delegated
      - /app/node_modules
    restart: unless-stopped
